### ISSUE TITLE
Getting back in touch?

### ISSUE THREAD

**Issue by Sigmanificient** [TrigonDev/hikari-clusters#8]
Hi, circuit! 

It has been a while since I've been able to reach you out, and i was looking at your Github profile from time to time in hope to find any sign of life from you.
Hope you remember me and the mCoding community on discord, we are missing you. Do you still have access to your discord? I would love to get back in touch and talk about some stuff!

- Sigma

**Comment by CircuitSacul** [comment]
@Sigmanificient Sorry for the slow response. I haven't forgotten about mCoding, and I'll come back soon. I've been off Discord for a while so I'm going to wait until Saturday to try and catch up on everything.
